/* Public interaction parity. Enquiry delivery stays on the original WordPress site. */
(() => {
const F=sourceFeatures,E=isEnglish,T=(en,ka)=>E?en:ka;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=(base,q='')=>pageName(base)+(q?'?'+q:'');
const main=document.getElementById('feature-content');
const idx=(key,max)=>{const n=Number(params.get(key)||0);return Number.isInteger(n)&&n>=0&&n<max?n:0;};
const button=(text,attrs='')=>'<button type="button" class="btn secondary" '+attrs+'>'+esc(text)+'</button>';
const original=(url,text)=>'<a class="original-link" href="'+esc(url)+'" target="_blank" rel="noopener">'+esc(text)+' ↗</a>';
const section=(title,body)=>'<section><div class="container"><div class="section-head"><h2>'+title+'</h2></div>'+body+'</div></section>';
const hero=(title,subtitle='')=>'<header class="pagehero"><div class="container"><div class="breadcrumbs"><a href="'+pageName('index')+'">'+T('Home','მთავარი')+'</a> / '+esc(title)+'</div><h1>'+esc(title)+'</h1><p>'+esc(subtitle)+'</p></div></header>';
function categoryCards(){return F.categories.map((c,i)=>'<a class="service-link" href="'+link('category','id='+i)+'"><span class="num">'+String(i+1).padStart(2,'0')+'</span><span>'+esc(E?c.en:c.title)+'</span><small>'+c.services.length+' '+T('specialist services','სერვისი')+' →</small></a>').join('');}
function serviceCards(ids){return ids.map(i=>'<a class="service-link" href="'+link('service','id='+i)+'"><span>'+esc(data[i][0])+'</span><small>'+esc(data[i][1])+'</small></a>').join('');}
// Use the full original company wordmark.
document.querySelectorAll('.brand').forEach(a=>{const img=a.querySelector('img');if(img){img.src='https://cleanservice.ge/wp-content/uploads/2026/03/CS-LOGO.png';img.alt='Cleanservice.ge';a.classList.add('original-brand');a.querySelector('span')?.remove();}});
// Preserve every query parameter when changing languages, including product/category filters.
document.querySelectorAll('.language-switch a').forEach(a=>{const english=a.lang==='en';a.href=pageName(baseFile.replace('.html',''),english)+location.search;});
const navigation=document.getElementById('navigation');
function dropdown(label,href,items){return '<div class="nav-group"><a href="'+href+'">'+label+'</a><button type="button" class="submenu-toggle" aria-expanded="false" aria-label="'+esc(label+' '+T('submenu','ქვემენიუ'))+'">⌄</button><div class="submenu" hidden>'+items+'</div></div>';}
if(navigation){
 const catLinks=F.categories.map((c,i)=>'<a href="'+link('category','id='+i)+'">'+esc(E?c.en:c.title)+'</a>').join('');
 const rentalLinks=[['rental',T('Extraction & cleaning equipment','ქიმწმენდის აპარატების ქირაობა')],['steam',T('Steam cleaner rental','ორთქლის აპარატების ქირაობა')],['sale',T('Equipment for sale','გასაყიდი აპარატები')]].map(([filter,name])=>'<a href="'+link('rentals','type='+filter)+'">'+name+'</a>').join('')+'<a href="https://cleanshop.ge/" target="_blank" rel="noopener">'+T('Cleaning supplies','საწმენდი საშუალებები')+' ↗</a>';
 const extra='<a href="'+link('media')+'">'+T('Media','მედია')+'</a><a href="'+link('join')+'">'+T('Join our team','შემოგვიერთდით')+'</a>';
 navigation.innerHTML='<a href="'+link('index')+'">'+T('Home','მთავარი')+'</a>'+dropdown(T('Services','სერვისები'),link('services'),catLinks)+dropdown(T('Equipment','გაქირავება'),link('rentals'),rentalLinks)+dropdown(T('Journal','ბლოგი'),link('blog'),F.links.filter((x,i,a)=>['რემონტის შემდგომი დალაგება','ავეჯის ქიმწმენდა','რბილი ავეჯის ქიმწმენდა','ავეჯის ქიმწმენდა თბილისში','ქიმწმენდის აპარატის უპირატესობები','5 მიზეზი, თუ რატომ უნდა დაიქირავო cleanservice.ge','აუზის მოვლა: გენერალური და გეგმიური წმენდა/დასუფთავება'].includes(x.text)&&a.findIndex(v=>v.url===x.url)===i).map((x,i)=>'<a href="'+esc(x.url)+'" target="_blank" rel="noopener">'+esc(E?['Post-renovation cleaning','Furniture cleaning','Upholstery cleaning','Furniture cleaning in Tbilisi','Benefits of extraction cleaners','5 reasons to choose Cleanservice','Pool care'][i]:x.text)+' ↗</a>').join(''))+dropdown(T('More','მეტი'),link('media'),extra)+'<a href="'+link('contact')+'">'+T('Contact','კონტაქტი')+'</a>';
 navigation.querySelectorAll('.submenu-toggle').forEach(b=>b.addEventListener('click',()=>{const open=b.getAttribute('aria-expanded')!=='true';navigation.querySelectorAll('.submenu-toggle').forEach(x=>{x.setAttribute('aria-expanded','false');x.nextElementSibling.hidden=true;});b.setAttribute('aria-expanded',String(open));b.nextElementSibling.hidden=!open;}));
 document.addEventListener('click',e=>{if(!navigation.contains(e.target))navigation.querySelectorAll('.submenu-toggle').forEach(b=>{b.setAttribute('aria-expanded','false');b.nextElementSibling.hidden=true;});});
 document.addEventListener('keydown',e=>{if(e.key==='Escape')navigation.querySelectorAll('.submenu-toggle').forEach(b=>{b.setAttribute('aria-expanded','false');b.nextElementSibling.hidden=true;});});
}
// Dialog shared by original live forms and image galleries.
const modal=document.createElement('dialog');modal.className='feature-dialog';modal.setAttribute('aria-label',T('Details','დეტალები'));document.body.append(modal);
function showDialog(body){modal.innerHTML='<button type="button" class="dialog-close" aria-label="'+T('Close','დახურვა')+'">×</button>'+body;modal.querySelector('.dialog-close').onclick=()=>modal.close();modal.showModal();}
modal.addEventListener('close',()=>{modal.innerHTML='';});modal.addEventListener('click',e=>{if(e.target===modal)modal.close();});
function openOriginalForm(join=false){const url=join?F.join:'https://cleanservice.ge/contact/';showDialog('<div class="dialog-heading"><h2>'+T(join?'Join the Cleanservice team':'Book a callback',join?'შემოგვიერთდით':'ჩანიშნეთ გამოძახება')+'</h2><p>'+T('Complete the live form on cleanservice.ge. Your enquiry is handled by the original website.','შეავსეთ მოქმედი ფორმა cleanservice.ge-ზე. მოთხოვნას მიიღებს ორიგინალი ვებსაიტი.')+'</p>'+original(url,T('Open the original form in a new tab','გახსენით ორიგინალი ფორმა ახალ ჩანართში'))+'</div><iframe class="original-form-frame" title="'+T('Original Cleanservice form','Cleanservice-ის ორიგინალი ფორმა')+'" src="'+esc(url)+'" loading="eager"></iframe>');}
function gallery(images,start=0){let current=start;function render(){const image=images[current];showDialog('<div class="gallery-view"><img src="'+esc(image.src||image)+'" alt="'+esc(image.alt||T('Equipment / cleaning gallery','გალერეა'))+'"><div class="gallery-controls">'+button('←','data-prev')+'<span aria-live="polite">'+(current+1)+' / '+images.length+'</span>'+button('→','data-next')+'</div></div>');modal.querySelector('[data-prev]').onclick=()=>{current=(current+images.length-1)%images.length;render();};modal.querySelector('[data-next]').onclick=()=>{current=(current+1)%images.length;render();};}render();}
document.addEventListener('click',event=>{const target=event.target.closest('[data-book],[data-join]');if(target){event.preventDefault();openOriginalForm(target.hasAttribute('data-join'));}});
// Existing booking CTAs now open the real form instead of an email draft.
document.querySelectorAll('a').forEach(a=>{if(/^(Book a visit|ჩანიშნეთ გამოძახება)$/.test(a.textContent.trim()))a.setAttribute('data-book','');});
if(baseFile==='contact.html'){
 const form=document.querySelector('.form');if(form){const box=document.createElement('div');box.className='form live-form-entry';box.innerHTML='<span class="eyebrow">'+T('Request a callback','ჩანიშნეთ გამოძახება')+'</span><h2>'+T('Choose your time and location','შეათანხმეთ სასურველი დრო და ლოკაცია')+'</h2><p>'+T('The original callback form asks for your name, email address and phone number. Use the live form to send your request directly to Cleanservice.','ფორმა ითხოვს სახელს, ელ.ფოსტას და ტელეფონის ნომერს. გაგზავნეთ მოთხოვნა Cleanservice-ის მოქმედი ფორმით.')+'</p>'+button(T('Open live enquiry form','გახსენით მოქმედი ფორმა'),'data-book')+'<p class="form-note">'+T('Opens the original website’s form. No request is sent until you submit it there.','გაიხსნება ორიგინალი საიტის ფორმა. მოთხოვნა იგზავნება მხოლოდ იქ დადასტურების შემდეგ.')+'</p>';form.replaceWith(box);}
 const contact=document.querySelector('.contact-card');contact?.insertAdjacentHTML('beforeend',original('https://maps.app.goo.gl/jygbCvuMuY8B274C8',T('Directions in Google Maps','Google რუკაზე ნახვა'))+'<p><a href="'+link('join')+'">'+T('Join our team','შემოგვიერთდით')+' →</a></p>');
}
if(baseFile==='services.html'){
 const list=document.querySelector('[data-services]');list.innerHTML=categoryCards();
}
if(baseFile==='category.html'){
 const c=F.categories[idx('id',F.categories.length)];document.title=(E?c.en:c.title)+' | Cleanservice';
 main.innerHTML=hero(E?c.en:c.title,E?c.services.map(i=>data[i][0]).join(' · '):c.intro)+section(T('Choose your service','აირჩიეთ სერვისი'),'<div class="service-list">'+serviceCards(c.services)+'</div>')+section(T('Service questions','ხშირად დასმული კითხვები'),'<div class="faq" lang="ka">'+(E?'<p class="form-note">Original questions and answers from Cleanservice, in Georgian.</p>':'')+c.faqs.map(f=>'<details><summary>'+esc(f.q)+'</summary><p>'+esc(f.a)+'</p></details>').join('')+'</div>');
}
if(baseFile==='service.html'){
 const detail=F.serviceDetails[serviceIndex];if(detail){const article=document.querySelector('.article');if(E){article.insertAdjacentHTML('beforeend','<details class="original-details"><summary>Full original service details & FAQs (Georgian)</summary><div lang="ka" class="source-content">'+detail.html+'</div></details>');}else{article.innerHTML='<div class="source-content">'+detail.html+'</div>';}}
}
function productCard(product){const id=F.products.indexOf(product);return '<article class="card product-card"><a href="'+link('product','id='+id)+'"><img loading="lazy" src="'+esc(product.image)+'" alt="'+esc(product.en)+'"><div class="card-body"><span class="tag">'+T(product.sale?'Equipment · Rental / sales':'Equipment rental',product.sale?'გაქირავება / გაყიდვა':'გაქირავება')+'</span><h3>'+esc(E?product.en:product.name)+'</h3><span class="card-link">'+T('View details','გაიგეთ მეტი')+' →</span></div></a></article>';}
if(baseFile==='rentals.html'){
 const old=document.querySelector('section');const catalogue=document.createElement('section');catalogue.innerHTML='<div class="container"><div class="catalogue-tabs" role="group" aria-label="'+T('Equipment categories','აპარატების კატეგორიები')+'">'+[['rental',T('Rental equipment','გასაქირავებელი აპარატები')],['steam',T('Steam cleaners','ორთქლის აპარატები')],['sale',T('For sale','გასაყიდი აპარატები')]].map(([v,l])=>button(l,'data-filter="'+v+'" aria-pressed="false"')).join('')+'</div><p>'+T('For current prices, availability and rental periods, call','ფასისა და დაჯავშნისთვის დაგვიკავშირდით:')+' <a href="tel:+995591484844">591 484 844</a>.</p><div class="grid3 catalogue-grid"></div><p>'+original('https://cleanshop.ge/',T('Shop cleaning supplies','საწმენდი საშუალებები'))+' · '+original('https://www.facebook.com/CHITASDETAILING',"Chita’s Detailing")+'</p></div>';old.replaceWith(catalogue);
 const render=type=>{catalogue.querySelector('.catalogue-grid').innerHTML=F.products.filter(p=>p[type]).map(productCard).join('');catalogue.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter===type)));};
 let type=['rental','steam','sale'].includes(params.get('type'))?params.get('type'):'rental';render(type);
 catalogue.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{type=b.dataset.filter;history.replaceState(null,'','?type='+type);document.querySelectorAll('.language-switch a').forEach(a=>{const u=new URL(a.href);u.search='?type='+type;a.href=u.href;});render(type);}));
}
if(baseFile==='product.html'){
 const id=idx('id',F.products.length),p=F.products[id];document.title=(E?p.en:p.name)+' | Cleanservice';
 const images=p.images.length?p.images:[p.image];
 main.innerHTML=hero(T('Equipment details','აპარატის დეტალები'))+'<section><div class="container product-layout"><div><button class="product-photo" data-product-image aria-label="'+T('Open image gallery','გალერეის გახსნა')+'"><img src="'+esc(images[0])+'" alt="'+esc(p.en)+'"><span>'+T('Click to enlarge','გასადიდებლად დააჭირეთ')+' ⤢</span></button></div><div><h2>'+esc(E?p.en:p.name)+'</h2><p>'+T('Contact Cleanservice for availability, pricing and the rental period.','ტექნიკა ქირავდება სხვადასხვა დროით. დასაჯავშნად დაგვიკავშირდით.')+'</p><a class="btn primary" href="tel:+995591484844">'+T('Call to enquire','დაგვირეკეთ')+' · 591 484 844</a><p>'+original(p.url,T('Original product page','ორიგინალი პროდუქტის გვერდი'))+'</p></div></div><div class="container product-tabs"><div role="tablist" aria-label="'+T('Product information','პროდუქტის ინფორმაცია')+'"><button role="tab" id="description-tab" aria-controls="description-panel" aria-selected="true">'+T('Description','აღწერა')+'</button><button role="tab" id="specs-tab" aria-controls="specs-panel" aria-selected="false" tabindex="-1">'+T('Additional information','დამატებითი ინფორმაცია')+'</button></div><div id="description-panel" role="tabpanel" aria-labelledby="description-tab" class="source-content">'+(E?'<p>Original manufacturer description supplied by Cleanservice (Georgian). Technical specification labels are available in English in the next tab.</p>':'')+'<div lang="ka">'+p.description+'</div></div><div id="specs-panel" role="tabpanel" aria-labelledby="specs-tab" hidden><table class="spec-table"><tbody>'+((E?p.enSpecs:p.specs).map(([a,b])=>'<tr><th scope="row">'+esc(a)+'</th><td>'+esc(b)+'</td></tr>').join('')||'<tr><td>'+T('No separate technical specification table is published for this product. See the description.','დამატებითი მახასიათებლებისთვის იხილეთ აღწერა.')+'</td></tr>')+'</tbody></table></div></div></section>'+section(T('Related equipment','მსგავსი პროდუქტები'),'<div class="grid3">'+F.products.filter(x=>x!==p&&(p.steam?x.steam:x.rental===p.rental)).slice(0,3).map(productCard).join('')+'</div>');
 main.querySelector('[data-product-image]').onclick=()=>gallery(images);
 const tabs=main.querySelectorAll('[role=tab]');function selectTab(selected){tabs.forEach(t=>{const active=t===selected;t.setAttribute('aria-selected',String(active));t.tabIndex=active?0:-1;document.getElementById(t.getAttribute('aria-controls')).hidden=!active;});}tabs.forEach((t,i)=>{t.onclick=()=>selectTab(t);t.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const target=tabs[e.key==='Home'?0:e.key==='End'?1:1-i];selectTab(target);target.focus();}};});
}
// The journal retains real original article destinations and original archive pagination.
if(baseFile==='blog.html'){
 const grid=document.querySelector('.blog-grid');grid.innerHTML=F.blog.posts.map((p,i)=>'<article class="blog-card"><a href="'+esc(p.url)+'" target="_blank" rel="noopener">'+(p.image?'<img loading="lazy" src="'+esc(p.image)+'" alt="">':'')+'<span class="tag">'+T('Original article · Georgian','სტატია')+'</span><h3 lang="ka">'+esc(p.title)+'</h3><span class="card-link">'+T('Read full article','სრულად წაკითხვა')+' ↗</span></a></article>').join('');
 grid.insertAdjacentHTML('afterend','<nav class="container archive-pagination" aria-label="'+T('Journal pages','ბლოგის გვერდები')+'"><span>'+T('Archive pages:','გვერდები:')+'</span><strong>1</strong>'+F.blog.pages.filter((a,i,all)=>a.url&&all.findIndex(x=>x.url===a.url)===i).map(a=>original(a.url,a.text.replace('Page ',''))).join('')+'</nav><p class="container form-note">'+T('Full articles and further archive pages open on the original Cleanservice website.','სრული სტატიები და არქივის სხვა გვერდები იხსნება ორიგინალ ვებსაიტზე.')+'</p>');
}
const socials=[['Facebook','https://www.facebook.com/cleanservicegeo/'],['Instagram','https://www.instagram.com/cleanservice.ge/?igsh=MWV6dmE5cjM4Z3c3Zw%3D%3D&utm_source=qr'],['TikTok','https://www.tiktok.com/@cleanservice.ge']];
const realImages=[...new Map(F.serviceDetails.filter(p=>p.image).map(p=>[p.image,{src:p.image,alt:T('Cleanservice cleaning work','Cleanservice სამუშაოები')}])).values()];
if(baseFile==='media.html'){
 main.innerHTML=hero(T('Cleanservice in action','მედია'),T('Follow our work and updates on social media.','ადევნე თვალი ქლინსერვისის სოციალურ ქსელებს'))+section(T('Watch our work','ნახე ჩვენი პრომო ვიდეო'),'<video class="promo-video" controls preload="metadata" playsinline src="'+esc(F.videos[1].src)+'"></video><div class="social-links">'+socials.map(([n,u])=>original(u,n)).join('')+'</div>')+section(T('Gallery','გალერეა'),'<div class="gallery-grid">'+realImages.map((img,i)=>'<button class="gallery-thumb" data-gallery="'+i+'" aria-label="'+T('Open image','ფოტოს გახსნა')+' '+(i+1)+'"><img loading="lazy" src="'+esc(img.src)+'" alt="'+esc(img.alt)+'"></button>').join('')+'</div>')+section(T('From our Facebook feed','Facebook სიახლეები'),'<div class="source-feed-links">'+F.mediaLinks.filter(x=>/posts|videos|reel|photo/.test(x.url)).slice(0,8).map((x,i)=>original(x.url,T('View post','პოსტის ნახვა')+' '+(i+1))).join('')+'</div>'+original('https://www.facebook.com/cleanservicegeo/',T('Open the live Facebook feed','ნახეთ Facebook გვერდი')));
 main.querySelectorAll('[data-gallery]').forEach(b=>b.onclick=()=>gallery(realImages,Number(b.dataset.gallery)));
}
if(baseFile==='join.html'){
 main.innerHTML=hero(T('Join the Cleanservice team','შემოგვიერთდით'),T('If you are hardworking, punctual, attentive to detail and enjoy helping people, we would like to hear from you.','თუ ხარ შრომისმოყვარე, პუნქტუალური, დეტალებზე ორიენტირებული და გსურს დასაქმება, მოგვწერე ან შეავსე ფორმა.'))+section(T('Application form','სააპლიკაციო ფორმა'),'<div class="join-panel"><p>'+T('The original application asks for your first and last name, phone, email, address and work experience.','მიუთითეთ სახელი, გვარი, ტელეფონი, ელ.ფოსტა, მისამართი და სამუშაო გამოცდილება.')+'</p>'+button(T('Open live application form','გახსენით სააპლიკაციო ფორმა'),'data-join')+'<p>'+original(F.join,T('Apply on cleanservice.ge','შეავსეთ ფორმა cleanservice.ge-ზე'))+'</p></div>');
}
if(baseFile==='index.html'){
 document.querySelectorAll('.grid3')[0]?.querySelectorAll('.card-link').forEach((a,i)=>a.href=link('category','id='+i));
 document.querySelector('.rental')?.querySelectorAll('.card-link').forEach((a,i)=>a.href=link('rentals','type='+['rental','steam','sale'][i]));
 const faq=document.querySelector('.faq');if(faq){faq.insertAdjacentHTML('beforeend','<details><summary>'+T('How much does cleaning cost?','ფასები რამდენად ხელმისაწვდომია?')+'</summary><p>'+T('The original FAQ lists post-renovation cleaning from ₾6/m², general cleaning from ₾5/m², carpet cleaning from ₾7/m² and hard floors from ₾3/m². An exact quote requires photos and depends on the work.','რემონტის შემდგომი დასუფთავება — 6₾-დან; გენერალური — 5₾-დან; რბილი იატაკი — 7₾-დან; მყარი იატაკი — 3₾-დან კვადრატულ მეტრზე. ზუსტი ფასისთვის გამოგვიგზავნეთ ფოტო.')+'</p></details><details><summary>'+T('Why choose on-site upholstery cleaning?','რა უპირატესობა აქვს ქიმწმენდას სახლში?')+'</summary><p>'+T('Save time and money, without having to transport your furniture.','დაზოგავთ დროს და ფულს, ავეჯის ტრანსპორტირების გარეშე.')+'</p></details>');}
 const heroActions=document.querySelector('.hero-actions');const watch=document.createElement('button');watch.type='button';watch.className='btn secondary';watch.textContent=T('▶ Watch our work','▶ ვიდეო');heroActions?.append(watch);watch.onclick=()=>showDialog('<div class="gallery-view"><video class="promo-video" controls autoplay playsinline src="'+esc(F.videos[0].src)+'"></video></div>');
 const showcase=document.createElement('section');showcase.className='service-showcase';showcase.innerHTML='<div class="container"><div class="section-head"><h2>'+T('Explore our cleaning services','ჩვენი დასუფთავების სერვისები')+'</h2><div class="gallery-controls">'+button('←','data-slide-prev')+button('→','data-slide-next')+'</div></div><div class="showcase-stage" aria-live="polite"></div><div class="showcase-dots"></div></div>';document.querySelector('.band')?.before(showcase);let activeSlide=0;const slideIds=[1,4,3,0,2,5];const stage=showcase.querySelector('.showcase-stage');function showSlide(){const id=slideIds[activeSlide],source=F.serviceDetails[id];stage.innerHTML='<img loading="lazy" src="'+esc(source.image)+'" alt="'+esc(data[id][0])+'"><div><span class="eyebrow">'+String(activeSlide+1).padStart(2,'0')+' / 06</span><h3>'+esc(data[id][0])+'</h3><p>'+esc(data[id][1])+'</p><a class="btn secondary" href="'+link('service','id='+id)+'">'+T('View service','სერვისის ნახვა')+' →</a></div>';showcase.querySelectorAll('[data-slide]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.slide)===activeSlide)));}showcase.querySelector('.showcase-dots').innerHTML=slideIds.map((_,i)=>'<button data-slide="'+i+'" aria-label="'+T('Go to slide','სლაიდზე გადასვლა')+' '+(i+1)+'" aria-pressed="false"></button>').join('');showcase.querySelectorAll('[data-slide]').forEach(b=>b.onclick=()=>{activeSlide=Number(b.dataset.slide);showSlide();});showcase.querySelector('[data-slide-prev]').onclick=()=>{activeSlide=(activeSlide+5)%6;showSlide();};showcase.querySelector('[data-slide-next]').onclick=()=>{activeSlide=(activeSlide+1)%6;showSlide();};showSlide();
 const partners=document.createElement('div');partners.className='container partner-strip';partners.setAttribute('aria-label',T('Brands shown by Cleanservice','Cleanservice ბრენდები'));partners.innerHTML=F.partners.map(src=>'<img loading="lazy" src="'+esc(src)+'" alt="Brand logo">').join('');showcase.after(partners);
 const cta=document.querySelector('.cta');const extra=document.createElement('div');extra.innerHTML=section(T('See the team at work','ნახე ჩვენი პრომო ვიდეო'),'<video class="promo-video" controls preload="none" playsinline poster="'+esc(realImages[0]?.src||'')+'" src="'+esc(F.videos[1].src)+'"></video>')+section(T('What our customers say','Google-ის შეფასებები'),'<div class="review-carousel"><div class="review-content" aria-live="polite"></div><div class="gallery-controls">'+button('←','data-review-prev')+button('→','data-review-next')+'</div></div><p class="form-note">'+T('Reviews shown on the original Cleanservice website. Open Google for current reviews.','შეფასებები ორიგინალი Cleanservice ვებსაიტიდან. მიმდინარე შეფასებები იხილეთ Google-ზე.')+'</p><div class="social-links">'+original('https://maps.app.goo.gl/jygbCvuMuY8B274C8',T('Read Google reviews','Google შეფასებები'))+original('https://admin.trustindex.io/api/googleWriteReview?place-id=ChIJGTSJvtlvREARM2o8w1vPIwI',T('Write a review','დაწერეთ მიმოხილვა'))+'</div>');cta.before(extra);
 let review=0;function renderReview(){const r=F.reviews[review];extra.querySelector('.review-content').innerHTML='<blockquote lang="ka">“'+esc(r.text)+'”</blockquote><strong>'+esc(r.name)+'</strong><span class="review-count">'+(review+1)+' / '+F.reviews.length+'</span>';};renderReview();extra.querySelector('[data-review-prev]').onclick=()=>{review=(review+F.reviews.length-1)%F.reviews.length;renderReview();};extra.querySelector('[data-review-next]').onclick=()=>{review=(review+1)%F.reviews.length;renderReview();};
}
const footer=document.querySelector('.footer .container');if(footer){footer.insertAdjacentHTML('beforeend','<div class="footer-extras"><div class="social-links">'+socials.map(([n,u])=>original(u,n)).join('')+original('https://maps.app.goo.gl/jygbCvuMuY8B274C8',T('Directions','რუკა'))+'</div><div class="social-links"><a href="'+link('media')+'">'+T('Media','მედია')+'</a><a href="'+link('join')+'">'+T('Join our team','შემოგვიერთდით')+'</a><a href="https://cleanshop.ge/" target="_blank" rel="noopener">Cleanshop.ge ↗</a></div></div>');}
// Functional links in imported source text stay local wherever a matching page exists.
document.querySelectorAll('.source-content a').forEach(a=>{const service=F.serviceDetails.findIndex(s=>s.url===a.href);if(service>=0)a.href=link('service','id='+service);else if(a.href==='https://cleanservice.ge/')a.href=link('index');else if(a.href==='https://cleanservice.ge/contact/')a.setAttribute('data-book','');});
})();
